export { default as HomePage } from '../../pages/headingIconsPages/HomePage'
export { default as ShortsPage } from '../../pages/headingIconsPages/ShortsPage'
export { default as SubscriptionPage } from '../../pages/headingIconsPages/SubscriptionPage'

export { default as YourChannel } from '../../pages/youIconsPages/YourChannel'
export { default as History } from '../../pages/youIconsPages/History'
export { default as PlayLists } from '../../pages/youIconsPages/PlayLists'
export { default as YourVideos } from '../../pages/youIconsPages/YourVideos'
export { default as WatchLater } from '../../pages/youIconsPages/WatchLater'
export { default as LikedVideos } from '../../pages/youIconsPages/LikedVideos'

export { default as FireshipPage } from '../../pages/subscriptionPages/FireshipPage'
export { default as TraversyMediaPage } from '../../pages/subscriptionPages/TraversyMediaPage'
export { default as KevinPowellPage } from '../../pages/subscriptionPages/KevinPowellPage'
export { default as WebDevSimplifiedPage } from '../../pages/subscriptionPages/WebDevSimplifiedPage'
export { default as CalebCurryPage } from '../../pages/subscriptionPages/CalebCurryPage'
export { default as SonnySanghaPage } from '../../pages/subscriptionPages/SonnySanghaPage'
export { default as DevelopedbyedPage } from '../../pages/subscriptionPages/DevelopedbyedPage'
export { default as TedTalkPage } from '../../pages/subscriptionPages/TedTalkPage'
export { default as BbcPage } from '../../pages/subscriptionPages/BbcPage'
export { default as ReutersPage } from '../../pages/subscriptionPages/ReutersPage'

export { default as TrendingPage } from '../../pages/explorePages/TrendingPage'
export { default as MusicPage } from '../../pages/explorePages/MusicPage'
export { default as MoviesTvPage } from '../../pages/explorePages/MoviesTvPage'
export { default as LivePage } from '../../pages/explorePages/LivePage'
export { default as GamingPage } from '../../pages/explorePages/GamingPage'
export { default as NewsPage } from '../../pages/explorePages/NewsPage'
export { default as SportsPage } from '../../pages/explorePages/SportsPage'
export { default as LearningPage } from '../../pages/explorePages/LearningPage'
export { default as PodcastsPage } from '../../pages/explorePages/PodcastsPage'
